### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by Akababa** [mattijn/gprof2dot_magic#1]
I get this error in jupyter notebook:
`PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Michael\\AppData\\Local\\Temp\\tmprpmbat6r.pstats'
`
This is probably due to NamedTemporaryFile not being openable on Windows:https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file

**Comment by mattijn** [comment]
Thanks for PR. I made this commit https://github.com/mattijn/gprof2dot_magic/commit/c239294b424bcc5974b20f28b7962a734b4a887e to solve the issue on windows!
Thanks for reporting!
